### PR TITLE
[WIP] haskell-build-backend for cabal (or possibly stack) support, and big code cleanup

### PR DESCRIPTION
**Pull request by lierdakil**
Request for comments

### CODE REVIEW

**Comment by lierdakil** [comment]
NB: https://github.com/atom/atom/issues/8313 blocks this.

**Comment by edsko** [comment]
I've switched to this branch and will start using it. Some first observations:

1. One immediate problem: the go-to-previous-error and go-to-next-error hotkeys don't seem to work; I have them set to `ctrl-cmd-n` and `ctrl-cmd-p` (unchanged from before) but they don't seem to trigger anything (key binding resolver doesn't show them as being resolved to anything either). 

2. Although the "Build" tab is immediately activated once you start building, typically there will be a lot of build messages; it would be nicer (I think) if the window would scroll down automatically (unless perhaps manually scrolled up). 

3. The other thing I happened to notice was this on the console:

```
Uncaught ReferenceError: bufferPt is not defined plugin-manager.coffee:217 
(anonymous function) plugin-manager.coffee:217 
module.exports.Emitter.emit /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82 
EditorControl.shouldShowTooltip editor-control.coffee:121 
(anonymous function) editor-control.coffee:56 
```

**Comment by lierdakil** [comment]
@edsko
1. i've dropped settings interface for keybindings, so try adding these to your keymap directly (Edit → Open Your Keymap):
```cson
'atom-text-editor[data-grammar~="haskell"]':
  'ctrl-cmd-n':'ide-haskell:next-error'
  'ctrl-cmd-p':'ide-haskell:prev-error'
```
This is documented in readme, and I plan on adding a gui to set these, but that's not present atm.
2. I've had the same thought, but still working on it.
3. Forgot to push latest updates. Please pull and try again, I believe I've fixed this a couple days back.

**Comment by edsko** [comment]
But the "Hotkey Next Error" and "Hotkey Prev Error" are still in the `ide-haskell` package settings?

**Comment by edsko** [comment]
Oh, it seems that the bug where `ide-haskell` captures the escape key even when there is no tool tip snuck back in, making it impossible to close the search dialogue.

**Comment by edsko** [comment]
(Adding the entries to the keymap manually fixes the problem.)

**Comment by lierdakil** [comment]
Atom seems to keep config settings even if they're not in schema. Not sure
how to make it "forget".
17 авг. 2015 г. 19:29 пользователь "Edsko de Vries" <
notifications@github.com> написал:

**Comment by lierdakil** [comment]
As for escape key, I can't reproduce it...

**Comment by lierdakil** [comment]
Okay, due to discussion in https://github.com/edsko/atom-cabal/pull/19, I've redesigned some parts of the interface, so that things like message types are not "set in stone", but are configurable (also, added customisable menus). This also moves most things to emitter interface, which may be a good thing or a bad thing, depending on your perspective. In any case, please pull both ide-haskell and ide-haskell-cabal.

**Comment by edsko** [comment]
Ok, pulled and installed `season`. Will give this a spin.

**Comment by edsko** [comment]
Got

```
Uncaught TypeError: Cannot read property 'delete' of null /Users/e/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process-base.coffee:65 
```

when disabling the `haskell-ghc-mod` package.

**Comment by edsko** [comment]
(And having a `-build-backend` but no `-ide-backend` should not be an warning that the `ide-backend` is required.)

**Comment by lierdakil** [comment]
Thanks for catching, published a hotfix for haskell-ghc-mod (that's not a critical error, and not related to build-backend stuff, btw).

You *can* disable warning in settings, and it's displayed if *either* ide-backend or build-backend is missing. I will change text to reflect that later. Point being, show type/info, insert type, etc are not available with *just* build-backend. Hence, a warning. But if users know what they're doing, they can just disable this warning and use ide-haskell with just one of those (or none at all, although I fail to imagine a valid use-case for that)

**Comment by edsko** [comment]
Oh, sure. I guess I should have added emphasis: .. having a -build-backend but no -ide-backend should not be an warning that the ide-backend is _required_. I guess the warning just needs updating.

**Comment by edsko** [comment]
By the way, not sure if this is a new faeture or whether it just wasn't working for me previously, but am loving the error markers!

**Comment by lierdakil** [comment]
image
You mean these things? They've been there for ages, long before atom-haskell org. Mouseover tooltips on markers are kinda new (more like, they didn't always work before)

**Comment by edsko** [comment]
Yup, those are the ones I mean. I never got them before.

**Comment by lierdakil** [comment]
I guess this has something to do with uri matching. I think I may have fixed something in passing when migrating to build-backend.

**Comment by lierdakil** [comment]
Yep, my memory serves correct. See this line: https://github.com/atom-haskell/ide-haskell-cabal/commit/8b2edc1687ce33722e1decaaadf1683eb6e3fee0#diff-643610b5d763a9da23ebe3f45245f5dcR88, uri needs to be fully qualified for markers to work.

**Comment by edsko** [comment]
Aha, I see. Good stuff :+1:

**Comment by lierdakil** [comment]
A tiny little update: build progress is actually displayed as a progress bar. Pull both ide-haskell and ide-haskell-cabal to get it.

I think we should probably tackle target selection? I'm not sure if I can do it on my own, since I'm mostly lost with ghcjs stuff (part of it is I couldn't get it to work properly on my system -- ghcjs I mean)

**Comment by edsko** [comment]
Ok, I can help with that, but I'm also in the middle of moving house so I kind of have my hands full. But I"ll try to find some time this week.

**Comment by lierdakil** [comment]
Thanks, I appreciate that.

**Comment by edsko** [comment]
So I started to take a look at this. Updated both `ide-haskell` and `ide-haskell-cabal` to the latest `build-backend` branch, and now its eems i don't hav a build command at all anymore?

**Comment by edsko** [comment]
Oh, you modified `master` directly, the `build-backend` branch on `ide-haskell-cabal` should go. Now I see. Sorry.

**Comment by lierdakil** [comment]
Yeah, since you merged that PR anyway, I've found no reason to push to that branch anymore...

**Comment by edsko** [comment]
Yeah, it's fine. I just couldn't see what was going on.

Incidentally, I suggest getting rid of the "Startup Message Ide Backend" option and instead in the "Use backend" provide two additional options: "Automatic" and "None".

**Comment by lierdakil** [comment]
Sounds good to me.

**Comment by edsko** [comment]
Ok, I've pushed to the `master` branch of `ide-backend-cabal`. It now calls into `cabal` on build and shows the parsed `.cabal` file. I only extract a few bits of information, but I think it's sufficient:

``` json
{
  "name": "test-package",
  "version": "0.1.0.0",
  "targets": [
    {
      "type": "library",
      "name": "test-package",
      "target": "lib:test-package"
    },
    {
      "type": "executable",
      "name": "test-package",
      "target": "exe:test-package"
    },
    {
      "type": "test-suite",
      "name": "test-suite",
      "target": "test:test-suite"
    }
  ]
}
```

Here `type` can be `library`, `executable`, `test-suite` or `benchmark`, `name` is the name of the component (defaults to the name of the package in the case of a library), and `target` is the target as cabal refers to it (so that argument can be used directly for `cabal build <target>`.

I haven't done anything with this information other than log it to the console. I'm out of time now, but at least the `ghcjs` bit of this extension is now complete.

**Comment by edsko** [comment]
Still bitten by the escape-tries-to-close-non-existent-tooltip-rather-than-close-multiple-cursors bug again. It's rare though, haven't yet figured out under which circumstances this happens (on `build-backend` branch).

**Comment by edsko** [comment]
Actually, perhaps it's related to the the atom bug you reported. Open atom, Haskell file already loaded (so that the package doesn't properly activate), now the escape-bug occurs. Close the file, reopen it, and now it works properly.

**Comment by lierdakil** [comment]
Seems like it. Apparently, key bindings are restored from some sort of saved state on reloads, but without active package, there is no corresponding command, so it just stops there.

It could be possible to work around this bug by adding activation hooks to language-haskell, probably, instead of relying on Atom's implementation. I still hope it gets fixed somewhere down the road though...

**Comment by lierdakil** [comment]
Oh, right, that key is in ide-haskell keymap, which is loaded before activation. That should be easy enough to fix.

**Comment by lierdakil** [comment]
I finally got around to implementing build target selection. I don't really like current interface for it though, but my ideas on improving it are extremely vague. Suggestions are welcome.

**Comment by edsko** [comment]
Ok, have updated my branch and will start using it. Not sure that asking for the build target on every call is the right thing to do. I don't know if you think it will be too slow to call into Cabal when we initialize the project, but if we did that, you could show the list of targets alongside the various tabs at the top of the panel?

**Comment by lierdakil** [comment]
There lies a problem: users can and will change cabal file after package is
initialized. I couldn't figure out an elegant solution for that in limited
time I had to work on it, so I used a "fallback" option for this for now.
If you have any suggestions, I'd love to hear those.

That said, I don't think that targets should be on output panel. If
possible, I'd prefer to get those into `Haskell IDE → Select build target`
menu or something along those lines.

2015-09-07 13:47 GMT+03:00 Edsko de Vries <notifications@github.com>:

**Comment by edsko** [comment]
I take it it's not possible to dynamically construct the contents of the menu? As in, when the user requests the "Select build target" menu, at that point read the `.cabal` file? (I suppose this _will_ certainly be possible if the options are not presented as submenu items.) Only danger here is that the user might select something, then change the `.cabal` file, and then end up with a target that doesn't exist anymore. I don't know if this is a huge deal.

**Comment by lierdakil** [comment]
Dynamic construction is only available for context menu for some reason. If
I drop the menu idea, then it becomes somewhat easier, but I'm not exactly
sure what the alternative would be.
17 сент. 2015 г. 9:44 пользователь "Edsko de Vries" <
notifications@github.com> написал:

**Comment by edsko** [comment]
Perhaps the current solution would be okay, if the most recently used option would always be at the top.

**Comment by lierdakil** [comment]
Okay, I think I have arrived at something more or less satisfactory with this by separating target selection from build command.

This is starting to look somewhat decent.

I also added a hack to `language-haskell` that should help with atom/atom#8313, which doesn't seem to be going anywhere right now...

I'm thinking about releasing this sooner rather than later. Do you think `ide-haskell-cabal` is somewhat ready for this? Documentation is certainly lacking...

**Comment by edsko** [comment]
Well I'm using this every day with `ide-haskell-cabal` and it seems to be stable. What kind of documentation do we need?

**Comment by lierdakil** [comment]
Some explaination about using multiple ghc versions in readme might be nice, since that's not an immediately obvious feature, IMO.

**Comment by edsko** [comment]
So I leave my editor occupy half my screen with (the other half has my irc client and my console). In the latest HEAD the layout is too wide (unnecessarily so, I think). Before calling build:

screen shot 2015-09-30 at 08 09 10

After calling build:

screen shot 2015-09-30 at 08 09 30

**Comment by edsko** [comment]
@lierdakil Added some basic docs https://github.com/atom-haskell/ide-haskell-cabal/commit/866f95aebe16ea7f5ddecf4462d485c35017e76f

**Comment by lierdakil** [comment]
Okay, fiddled around with css, hopefully last version is better.

**Comment by edsko** [comment]
Looks good.

**Comment by lierdakil** [comment]
Merged and released yesterday. Seems to be doing okay for now.

**Pull request merged**
